global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.124:9090']

  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['10.233.4.122:9108'] 

  - job_name: 'gitlab'
    static_configs:
      - targets: ['192.168.0.124:8080']
    metrics_path: '/-/metrics'
    scheme: http
    honor_labels: true

  - job_name: 'gitlab-runner'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
        action: keep
        regex: gitlab-runner;gitlab-runner  # Update with actual namespace and service name

  - job_name: 'renovate'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
        action: keep
        regex: renovate;renovate  # Update with actual namespace and service name

  - job_name: 'nexus'
    scrape_interval: 120s
    scrape_timeout: 120s
    static_configs:
      - targets: ['nexus.ellisbs.co.uk:443']
    metrics_path: '/service/metrics/prometheus'
    scheme: https
    basic_auth:
      username: 'admin'
      password: ''

  - job_name: 'sonarqube'
    scrape_interval: 120s
    scrape_timeout: 120s
    static_configs:
      - targets: ['sonarqube.ellisbs.co.uk:443']
    metrics_path: '/api/monitoring/metrics'
    scheme: https
    basic_auth:
      username: 'admin'
      password: ''
