apiVersion: v1
data:
  prometheus.scrape.yml: |
    global:
      scrape_interval: 30s  # Set the global scrape interval

    scrape_configs:
      - job_name: 'elasticsearch'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            action: keep
            regex: elasticsearch;elasticsearch  # Update with actual namespace and service name

      - job_name: 'gitlab'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            action: keep
            regex: gitlab;gitlab  # Update with actual namespace and service name

      - job_name: 'gitlab-runner'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            action: keep
            regex: gitlab-runner;gitlab-runner  # Update with actual namespace and service name

      - job_name: 'renovate'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            action: keep
            regex: renovate;renovate  # Update with actual namespace and service name

      - job_name: 'nexus'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            action: keep
            regex: nexus;nexus  # Update with actual namespace and service name

      - job_name: 'sonarqube'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
            action: keep
            regex: sonarqube;sonarqube  # Update with actual namespace and service name
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-03T22:07:01Z"
  name: prometheus-config
  namespace: prometheus
  resourceVersion: "2190881"
  uid: 79a37942-fa96-44f5-ac9b-e785795121c8
